version: "3"

services:
  app:
    build:
      context: app
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node/usr/src/app
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0 # configuracao default do mysql
    container_name: db
    restart: always # restar o container caso ele caia
    tty: true # se precisar usar o modo interativo
    environment:
      - MYSQL_DATABASE=filmcatalogs
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
